version: '3.9'

services:
  db-glpi-10:
    image: percona/percona-server:5.7
    container_name: $MYSQL_CONTAINER_NAME
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE 
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      TZ: $TIMEZONE
    command: 
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_general_ci
    networks:
      - glpi
    volumes:
      - percona_lib:/var/lib/mysql 
      - percona_log:/var/log/mysql      
  glpi-10:
    image: glpi-local
    container_name: glpi-local
    privileged: true
    hostname: $HOSTNAME
    environment:
      SSLCERTIFICATEFILE: $SSLCERTIFICATEFILE
      SSLCERTIFICATEKEYFILE: $SSLCERTIFICATEKEYFILE
      TIMEZONE: $TIMEZONE
      UPLOAD_MAX_FILESIZE: $UPLOAD_MAX_FILESIZE
      POST_MAX_SIZE: $POST_MAX_SIZE
      MYSQL_DATABASE: $MYSQL_DATABASE 
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD  
      MYSQL_CONTAINER_NAME: $MYSQL_CONTAINER_NAME    
    depends_on:
      - $MYSQL_CONTAINER_NAME   
    ports:
      - 80:80
      - 443:443
    volumes:
      - glpi_lib:/var/lib/glpi     
      - glpi_marketplace:/usr/share/glpi/marketplace           
      - glpi_etc:/etc/glpi
      - glpi_backup:/backup
      - certificados:/tmp/certificado
    networks:
      - glpi
  
networks:
  glpi:
    name: glpi
volumes:
  glpi_marketplace:
    name: glpi_marketplace
  glpi_lib:
    name: glpi_lib
  glpi_etc:
    name: glpi_etc
  glpi_backup:
    name: glpi_backup
  percona_lib:
      name: percona_lib
  percona_log:
    name: percona_log
  certificados:
    name: certificados
    external: true